cloud:
  aws:
    credentials:
      access-key: AKIAWU5BUUASCSGYFKYM
      secret-key: DQKoOkNEQ64+ex6+HaV7sXIlhdFTQXqPvA8I9x2G
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: yourself-app


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080